name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: |
          yarn test
